#include "std_testcase.h"

#include <stdexcept> 

using namespace std; 

namespace var1
{



void func1()
{
    int j;
    for(j = 0; j < 1; j++)
    {
        try
        {
            if (rand()%2 == 0)
            {
                throw out_of_range("err1");
            }
            if (rand()%2 == 0)
            {
                throw domain_error("err2");
            }
        }
        catch (exception &)
        {
            printLine("exception");
        }
        printLine("ok");
    }
}

} 



using namespace var1; 

int main(int argc, char * argv[])
{
    srand( (unsigned)time(NULL) );

    printLine("Calling ...");
    func1();
    printLine("Finished");
    return 0;
}

